version: "3"

services:
  app:
    image: 188469387653.dkr.ecr.us-east-2.amazonaws.com/todo:latest
    ports:
      - "8000:8000"
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=raja.db.elephantsql.com
      - DB_PORT=5432
      - DB_NAME=dbxmyroa
      - DB_USER=dbxmyroa
      - DB_PASS=ntAgoq5ArXXXKqaIdPz3wWs9suWnOwdC
      - JWT_SECRET=VERYSECRETIVETEXT
  nginx:
    image: nginx:1.15-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    links:
      - app
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  
  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
